#pragma once
#include "ExcepcionLugar.h"
#include "ExcepcionLugarOcupado.h"
#include "ExcepcionLugarReservado.h"
#include"ExcepcionParametro.h"
#include "ExcepcionRango.h"
#include "Computadora.h"
#include "Jugador.h"
#include"Persona.h"
#include "Juego.h"
#include "TableroIrregular.h"
#include "TableroGlobal.h"
#include "EstrategiaAleatoria.h"
#include "EstrategiaCentral.h"
#include "EstrategiaPeriferica.h"
#include "EstrategiaIsla.h"
#include "EstrategiaCercana.h"
#include "Originador.h"
#include "Memento.h"
#include "Repositorio.h"